export const workoutDatabase = {
  meta: {
    version: "1.0.0",
    description: "Comprehensive workout database for fitness web/mobile apps",
    units: "metric",
  },
  workoutCategories: [
    "Full Body",
    "Upper Body",
    "Lower Body",
    "Core",
    "Cardio",
    "HIIT",
    "Mobility",
    "Stretching",
  ],
  difficultyLevels: ["Beginner", "Intermediate", "Advanced"],
  equipmentTypes: [
    "None",
    "Dumbbells",
    "Barbell",
    "Resistance Band",
    "Kettlebell",
    "Pull-up Bar",
    "Machine",
    "Cable Machine",
    "Smith Machine",
    "Bench",
    "Mat",
  ],

  exercises: [
    {
      id: "ex_001",
      name: "Bodyweight Squat",
      category: "Lower Body",
      difficulty: "Beginner",
      equipment: "None",
      primaryMuscles: ["Quadriceps", "Glutes"],
      secondaryMuscles: ["Hamstrings", "Core"],
      instructions: [
        "Stand with feet shoulder-width apart",
        "Lower hips back and down",
        "Keep chest upright",
        "Return to standing",
      ],
      defaultReps: 15,
      defaultSets: 3,
      restSeconds: 45,
      caloriesPerMinute: 6,
    },
    {
      id: "ex_002",
      name: "Push-Up",
      category: "Upper Body",
      difficulty: "Beginner",
      equipment: "None",
      primaryMuscles: ["Chest", "Triceps"],
      secondaryMuscles: ["Shoulders", "Core"],
      instructions: [
        "Start in plank position",
        "Lower chest to floor",
        "Push back up while keeping body straight",
      ],
      defaultReps: 12,
      defaultSets: 3,
      restSeconds: 45,
      caloriesPerMinute: 7,
    },
    {
      id: "ex_003",
      name: "Plank",
      category: "Core",
      difficulty: "Beginner",
      equipment: "None",
      primaryMuscles: ["Core"],
      secondaryMuscles: ["Shoulders", "Glutes"],
      instructions: [
        "Elbows under shoulders",
        "Body in straight line",
        "Hold position",
      ],
      defaultDurationSeconds: 30,
      defaultSets: 3,
      restSeconds: 30,
      caloriesPerMinute: 4,
    },
    {
      id: "ex_004",
      name: "Jumping Jacks",
      category: "Cardio",
      difficulty: "Beginner",
      equipment: "None",
      primaryMuscles: ["Full Body"],
      instructions: [
        "Jump feet apart",
        "Raise arms overhead",
        "Return to start",
      ],
      defaultDurationSeconds: 40,
      defaultSets: 3,
      restSeconds: 20,
      caloriesPerMinute: 10,
    },
    {
      id: "ex_005",
      name: "Burpees",
      category: "HIIT",
      difficulty: "Advanced",
      equipment: "None",
      primaryMuscles: ["Full Body"],
      instructions: [
        "Squat down",
        "Jump feet back into plank",
        "Perform push-up",
        "Jump feet forward",
        "Explode up",
      ],
      defaultReps: 10,
      defaultSets: 3,
      restSeconds: 60,
      caloriesPerMinute: 14,
    },
    {
      id: "ex_006",
      name: "Forward Lunge",
      category: "Lower Body",
      difficulty: "Beginner",
      equipment: "None",
      primaryMuscles: ["Quadriceps", "Glutes"],
      secondaryMuscles: ["Hamstrings", "Core"],
      instructions: [
        "Step forward with one leg",
        "Lower until both knees are at 90 degrees",
        "Push back to start",
      ],
      defaultReps: 12,
      defaultSets: 3,
      restSeconds: 45,
      caloriesPerMinute: 6,
    },
    {
      id: "ex_007",
      name: "Glute Bridge",
      category: "Lower Body",
      difficulty: "Beginner",
      equipment: "Mat",
      primaryMuscles: ["Glutes", "Hamstrings"],
      secondaryMuscles: ["Core"],
      instructions: [
        "Lie on back with knees bent",
        "Drive hips up squeezing glutes",
        "Lower with control",
      ],
      defaultReps: 15,
      defaultSets: 3,
      restSeconds: 30,
      caloriesPerMinute: 5,
    },
    {
      id: "ex_008",
      name: "Chair Dips",
      category: "Upper Body",
      difficulty: "Beginner",
      equipment: "Bench",
      primaryMuscles: ["Triceps"],
      secondaryMuscles: ["Shoulders", "Chest"],
      instructions: [
        "Place hands on edge of chair/bench",
        "Lower body by bending elbows",
        "Push back up to start",
      ],
      defaultReps: 12,
      defaultSets: 3,
      restSeconds: 45,
      caloriesPerMinute: 5,
    },
    {
      id: "ex_009",
      name: "Wall Sit",
      category: "Lower Body",
      difficulty: "Beginner",
      equipment: "None",
      primaryMuscles: ["Quadriceps"],
      instructions: [
        "Slide back against a wall",
        "Hold knees at 90 degrees",
        "Maintain steady breathing",
      ],
      defaultDurationSeconds: 45,
      defaultSets: 3,
      restSeconds: 45,
      caloriesPerMinute: 4,
    },
    {
      id: "ex_010",
      name: "Mountain Climbers",
      category: "Cardio",
      difficulty: "Beginner",
      equipment: "Mat",
      primaryMuscles: ["Core"],
      secondaryMuscles: ["Shoulders", "Legs"],
      instructions: [
        "Start in plank",
        "Drive knees toward chest alternately",
        "Keep hips low and core engaged",
      ],
      defaultDurationSeconds: 40,
      defaultSets: 3,
      restSeconds: 30,
      caloriesPerMinute: 9,
    },
    {
      id: "ex_011",
      name: "High Knees",
      category: "Cardio",
      difficulty: "Beginner",
      equipment: "None",
      primaryMuscles: ["Full Body"],
      instructions: [
        "Run in place lifting knees high",
        "Pump arms to maintain rhythm",
      ],
      defaultDurationSeconds: 30,
      defaultSets: 3,
      restSeconds: 30,
      caloriesPerMinute: 11,
    },
    {
      id: "ex_012",
      name: "Barbell Back Squat",
      category: "Lower Body",
      difficulty: "Intermediate",
      equipment: "Barbell",
      primaryMuscles: ["Quadriceps", "Glutes"],
      secondaryMuscles: ["Hamstrings", "Core"],
      instructions: [
        "Position bar on upper back",
        "Squat down keeping chest up",
        "Drive through heels to stand",
      ],
      defaultReps: 8,
      defaultSets: 4,
      restSeconds: 120,
      caloriesPerMinute: 8,
    },
    {
      id: "ex_013",
      name: "Deadlift",
      category: "Lower Body",
      difficulty: "Advanced",
      equipment: "Barbell",
      primaryMuscles: ["Hamstrings", "Glutes", "Lower Back"],
      secondaryMuscles: ["Core"],
      instructions: [
        "Hinge at hips keeping back neutral",
        "Drive through heels to stand",
        "Lower the bar with control",
      ],
      defaultReps: 6,
      defaultSets: 4,
      restSeconds: 150,
      caloriesPerMinute: 9,
    },
    {
      id: "ex_014",
      name: "Bench Press",
      category: "Upper Body",
      difficulty: "Intermediate",
      equipment: "Barbell",
      primaryMuscles: ["Chest", "Triceps"],
      secondaryMuscles: ["Shoulders"],
      instructions: [
        "Lie on bench with feet planted",
        "Lower bar to chest",
        "Press back to full extension",
      ],
      defaultReps: 8,
      defaultSets: 4,
      restSeconds: 120,
      caloriesPerMinute: 7,
    },
    {
      id: "ex_015",
      name: "Lat Pulldown",
      category: "Upper Body",
      difficulty: "Intermediate",
      equipment: "Cable Machine",
      primaryMuscles: ["Lats"],
      secondaryMuscles: ["Biceps", "Rear Delts"],
      instructions: [
        "Grip bar wide",
        "Pull down to upper chest",
        "Control the return",
      ],
      defaultReps: 10,
      defaultSets: 3,
      restSeconds: 90,
      caloriesPerMinute: 6,
    },
    {
      id: "ex_016",
      name: "Seated Cable Row",
      category: "Upper Body",
      difficulty: "Intermediate",
      equipment: "Cable Machine",
      primaryMuscles: ["Back"],
      secondaryMuscles: ["Biceps"],
      instructions: [
        "Sit with knees slightly bent",
        "Pull handle to torso squeezing shoulder blades",
        "Control the release",
      ],
      defaultReps: 10,
      defaultSets: 3,
      restSeconds: 90,
      caloriesPerMinute: 6,
    },
    {
      id: "ex_017",
      name: "Dumbbell Shoulder Press",
      category: "Upper Body",
      difficulty: "Intermediate",
      equipment: "Dumbbells",
      primaryMuscles: ["Deltoids"],
      secondaryMuscles: ["Triceps"],
      instructions: [
        "Press dumbbells overhead with control",
        "Avoid shrugging shoulders",
      ],
      defaultReps: 10,
      defaultSets: 3,
      restSeconds: 90,
      caloriesPerMinute: 6,
    },
    {
      id: "ex_018",
      name: "Leg Press",
      category: "Lower Body",
      difficulty: "Intermediate",
      equipment: "Machine",
      primaryMuscles: ["Quadriceps", "Glutes"],
      secondaryMuscles: ["Hamstrings"],
      instructions: [
        "Place feet on platform",
        "Lower platform until knees are at ~90 degrees",
        "Press back to start",
      ],
      defaultReps: 10,
      defaultSets: 3,
      restSeconds: 90,
      caloriesPerMinute: 7,
    },
    {
      id: "ex_019",
      name: "Cable Triceps Pushdown",
      category: "Upper Body",
      difficulty: "Beginner",
      equipment: "Cable Machine",
      primaryMuscles: ["Triceps"],
      instructions: [
        "Hold bar with an overhand grip",
        "Extend elbows to push the bar down",
        "Control the return",
      ],
      defaultReps: 12,
      defaultSets: 3,
      restSeconds: 60,
      caloriesPerMinute: 5,
    },
  ],

  workoutTemplates: [
    {
      id: "wk_001",
      name: "10-Minute Busy Day Workout",
      difficulty: "Beginner",
      estimatedDurationMinutes: 10,
      goal: "General Fitness",
      exercises: [
        { exerciseId: "ex_001", sets: 2, reps: 15 },
        { exerciseId: "ex_002", sets: 2, reps: 10 },
        { exerciseId: "ex_004", sets: 2, durationSeconds: 40 },
      ],
    },
    {
      id: "wk_002",
      name: "Core Strength Builder",
      difficulty: "Intermediate",
      estimatedDurationMinutes: 15,
      goal: "Core Strength",
      exercises: [
        { exerciseId: "ex_003", sets: 3, durationSeconds: 40 },
        { exerciseId: "ex_002", sets: 3, reps: 12 },
      ],
    },
  ],
} as const;

export type WorkoutDatabase = typeof workoutDatabase;

export default workoutDatabase;
